"""create tours and tour_bookings tables

Revision ID: 6b3646124d0e
Revises: 6cb86ee384dc
Create Date: 2026-08-17 11:33:23.226452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3646124d0e'
down_revision: Union[str, Sequence[str], None] = '6cb86ee384dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('max_group_size', sa.Integer(), nullable=True),
    sa.Column('included_facilities', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_destination'), 'tours', ['destination'], unique=False)
    op.create_index(op.f('ix_tours_id'), 'tours', ['id'], unique=False)
    op.create_index(op.f('ix_tours_tour_type'), 'tours', ['tour_type'], unique=False)
    op.create_table('tour_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('num_people', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_bookings_id'), 'tour_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_tour_bookings_tour_id'), 'tour_bookings', ['tour_id'], unique=False)
    op.create_index(op.f('ix_tour_bookings_user_id'), 'tour_bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_bookings_user_id'), table_name='tour_bookings')
    op.drop_index(op.f('ix_tour_bookings_tour_id'), table_name='tour_bookings')
    op.drop_index(op.f('ix_tour_bookings_id'), table_name='tour_bookings')
    op.drop_table('tour_bookings')
    op.drop_index(op.f('ix_tours_tour_type'), table_name='tours')
    op.drop_index(op.f('ix_tours_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_destination'), table_name='tours')
    op.drop_table('tours')
    # ### end Alembic commands ###
